### ISSUE TITLE
Addind padding in KaggleDataset for smaller images

### ISSUE THREAD

**Issue by dbeu** [DangHa/Kaggle-HuBMAP-HPA#17]
There is a problem for images such as img 29, which are smaller and therefore can't be stacked together bu the DataLoader batcher 
for training. The __gettitem__ method should add padding to those images.

**Comment by DangHa** [comment]
I see another issue in the function `remove_white_area()`
Because I cutting it from [240:2800], so the smallest image which is able to be cut is 2800.

I will rewrite this function. Also, I have read your code, I will transfer it to the python code in another branch tomorrow. @dbeu

**Comment by DangHa** [comment]
[392d8b8](https://github.com/DangHa/Kaggle-HuBMAP-HPA/commit/392d8b8d9fc0894309232732b31a3d6d14a409f5)
